# This file contains the complete scandal template reorganization
# Copy these into investment_sim.py to replace the existing templates

LOW_SEVERITY_SCANDAL_TEMPLATES = {
    "Technology": [
        "{company} minor data leak exposes 500K email addresses, offering credit monitoring",
        "{company} software bug affects small subset of users, patch being developed",
        "{company} executive sells shares ahead of earnings, raising eyebrows but not illegal",
        "{company} advertising platform accused of minor privacy violations, regulators reviewing",
        "{company} customer service response times criticized, users complaining on social media",
        "{company} minor security flaw discovered in older products, fix being rolled out",
        "{company} lawsuit filed over misleading marketing claims for budget product line",
        "{company} third-party app integration breaks, causing temporary inconvenience for users",
        "{company} minor patent infringement claim filed by small competitor",
        "{company} controversial employee memo leaked, HR investigating workplace culture",
        "{company} quarterly revenue slightly below guidance, citing market headwinds",
        "{company} app crashes affecting Android users, iOS version working normally",
        "{company} product launch delayed by 3 weeks due to last-minute quality checks",
        "{company} customer complaints about subscription billing errors spike 40%",
        "{company} minor API downtime affects third-party developers for 2 hours",
    ],
    "Electronics": [
        "{company} minor recall of 100K devices for cosmetic defect, no safety risk",
        "{company} supply chain delays push holiday product availability back 2 weeks",
        "{company} warranty claims increase 30% for specific product line",
        "{company} customer reviews cite minor quality control issues with new release",
        "{company} packaging errors result in wrong accessories shipped with products",
        "{company} component supplier raises prices, margin pressure expected",
        "{company} minor display issue reported in 2% of flagship devices",
        "{company} software update causes battery drain complaints from users",
        "{company} production line stoppage for 3 days due to equipment calibration",
        "{company} alleged worker overtime violations at contract manufacturer facility",
        "{company} product availability issues in European markets due to logistics delays",
        "{company} minor patent dispute with component supplier under arbitration",
    ],
    "Pharmaceuticals": [
        "{company} minor manufacturing deviation requires batch retesting, no recall needed",
        "{company} clinical trial enrollment slower than expected, timeline extended 2 months",
        "{company} minor labeling error on non-critical medication, corrective action issued",
        "{company} former employee files wrongful termination lawsuit, no merit apparent",
        "{company} generic competitor announces earlier-than-expected market entry",
        "{company} FDA requests minor clarification on drug application, routine matter",
        "{company} patient advocacy group criticizes pricing of specialty medication",
        "{company} supply shortage for non-essential product line due to ingredient availability",
        "{company} minor adverse event reports increase but within normal range",
        "{company} competitor's drug shows slightly better results in head-to-head study",
        "{company} pharmaceutical sales rep training practices questioned by ethics watchdog",
        "{company} clinical trial site audit reveals minor documentation issues",
    ],
    "Automotive": [
        "{company} minor recall of 80K vehicles for software update, no accidents reported",
        "{company} consumer group rates new model below competitors in satisfaction survey",
        "{company} delivery targets missed by 10% due to parts availability",
        "{company} minor paint defect reported on specific color option",
        "{company} customer complaints about infotainment system bugs increase",
        "{company} dealership network reports lower-than-expected profit margins",
        "{company} vehicle pricing criticized as too high relative to features",
        "{company} manufacturing plant experiences brief work slowdown over contract dispute",
        "{company} minor design flaw requires retrofit for existing vehicles, covered under warranty",
        "{company} safety rating comes in below expectations, still passes requirements",
        "{company} supplier announces price increase for key components",
        "{company} fleet customers report higher maintenance costs than anticipated",
    ],
    "Energy": [
        "{company} minor pipeline leak contained quickly, no environmental damage",
        "{company} quarterly production figures come in 5% below analyst estimates",
        "{company} equipment malfunction causes brief shutdown at small facility",
        "{company} environmental group protests new drilling permit application",
        "{company} minor safety violation cited at offshore platform, corrective action taken",
        "{company} commodity price fluctuations squeeze profit margins",
        "{company} exploration well results disappointing but not unexpected",
        "{company} regulatory approval for expansion project delayed by 6 weeks",
        "{company} worker injury at facility prompts safety review, operations continue",
        "{company} emissions slightly above permitted levels for one quarter, fines minimal",
        "{company} competing bid wins contract for new extraction rights",
        "{company} maintenance costs higher than forecast at aging facilities",
    ],
    "Mana Extraction": [
        "{company} minor rift instability requires temporary production reduction",
        "{company} dimensional energy prices soften, affecting quarterly margins",
        "{company} arcane equipment requires unscheduled maintenance, brief downtime",
        "{company} worker reports minor mana exposure, treated and released",
        "{company} Wizards' Council inspects facility, cites minor compliance issues",
        "{company} competing extractor discovers new rift, potentially affecting market share",
        "{company} interdimensional drilling permit renewal delayed by bureaucracy",
        "{company} mana purity levels fluctuate, requiring additional processing",
        "{company} reality stabilization costs increase due to regulatory changes",
        "{company} minor dimensional anomaly detected near extraction site, monitoring",
        "{company} rift worker union demands wage increase, negotiations ongoing",
        "{company} dimensional customs increases tariffs on cross-realm energy exports",
    ],
    "Golem Manufacturing": [
        "{company} minor software glitch requires patch for 1,000 deployed golems",
        "{company} production delays due to rare earth mineral supply constraints",
        "{company} golem efficiency 8% below specifications in field tests",
        "{company} customer opts for competitor's cheaper model, contract lost",
        "{company} maintenance costs higher than projected for older golem models",
        "{company} minor workplace incident with golem, worker uninjured",
        "{company} AI ethics board questions golem labor practices, review pending",
        "{company} golem operating system update causes minor compatibility issues",
        "{company} component supplier quality issues slow production line",
        "{company} customer satisfaction survey shows decline in support ratings",
        "{company} golem rental returns increase due to performance concerns",
        "{company} regulatory agency requests additional safety documentation",
    ],
    "Rare Fantasy Goods": [
        "{company} minor authentication dispute over recently acquired artifact",
        "{company} dimensional customs delays shipment of new inventory",
        "{company} competitor outbids for moderately valuable relic at auction",
        "{company} storage facility requires expensive upgrades for compliance",
        "{company} rare goods market softens, inventory valuation declines slightly",
        "{company} alleged misrepresentation of artifact provenance, investigation pending",
        "{company} shipping costs increase due to interdimensional trade restrictions",
        "{company} minor containment breach, low-value item lost to void",
        "{company} artifact appraisal comes in lower than purchase price",
        "{company} cosmic storm delays acquisition expedition by 4 weeks",
        "{company} celebrity collector switches to rival dealer for major purchase",
        "{company} insurance premiums increase for exotic goods coverage",
    ],
    "Magical Publishing": [
        "{company} spell typo in new grimoire edition, errata sheet being printed",
        "{company} enchanted paper supplier raises prices, margin pressure ahead",
        "{company} author contract dispute delays new series launch",
        "{company} competitor releases similar spellbook at lower price point",
        "{company} print run quality issues require partial reprint",
        "{company} distribution delays affect availability in key markets",
        "{company} book returns increase as readers report minor spell inaccuracies",
        "{company} magical academy adopts competitor's textbook series",
        "{company} copyright claim filed over spell collection, likely settled",
        "{company} printing press requires expensive maintenance overhaul",
        "{company} bestselling author considering move to rival publisher",
        "{company} customer complaints about binding quality on premium editions",
    ],
    "Divine Services": [
        "{company} blessing wait times increase to 3 weeks, customer frustration growing",
        "{company} miracle success rate dips to 94%, still above industry average",
        "{company} minor ritual equipment malfunction delays services for 2 days",
        "{company} deity partnership renegotiation stalls over revenue sharing",
        "{company} competitor offers faster resurrection service at similar price",
        "{company} holy water potency varies batch-to-batch, quality control review initiated",
        "{company} priest shortage in growing markets limits expansion plans",
        "{company} customer survey shows declining satisfaction with divine hotline response times",
        "{company} blessing costs increase due to sacred component price hikes",
        "{company} minor accounting error in indulgence sales reporting, correcting",
        "{company} religious authority questions marketing claims for miracle service",
        "{company} competitor's new deity partnership threatens market share",
    ],
}
